services:
  valheim-server:
    image: "ghcr.io/lloesche/valheim-server"
    user: "${PUID:-0}:${PGID:-0}"

    cap_add:
      - "SYS_NICE"
    stop_grace_period: "2m"
    ports:
      - "2456-2457:2456-2457/udp"
      # Comment out the following line if you don't want to expose Supervisor's HTTP port
      - "9001:9001/tcp"
      # Comment out the following line if you don't want to expose the Status Web Server HTTP port
      - "80:80/tcp"
    volumes:
      - "/valheim/config:/config"
      - "/valheim/data:/opt/valheim"
    restart: "unless-stopped"
    env_file: ".env"
